### ISSUE TITLE
Can't play with a friend

### ISSUE THREAD

**Issue by StellaThimoty** [WE-Kaito/digimon-tcg-simulator#109]
I openend inspect element and found that

Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

index-80366852.js:65

There's also this warning
Mixed Content: The page at 'https://www.digi-tcg.online/game' was loaded over HTTPS, but requested an insecure element 'http://assets.iceable.com/img/noise-transparent.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

I'm not using adblockers and I'm able to play with other people except that player, named Bibi_Rulez

EDIT: I tested this on Firefox, Vivaldi and Chrome, same situation in all browsers

**Comment by WE-Kaito** [comment]
- Explains why sounds are not played on the first visit of the game page. 🤔
- I see, should have saved that picture as an asset.
- omg, I never thought of that: 
in the frontend, the gameId is saved as `invitedUser + "_" + invitingUser` and later split by "_" to determine player 1 and 2. So I should either now allow "_" to be in a name or split the gameID by something else.

Thank you for that insightful request! Puhsing some fixes now

**Comment by WE-Kaito** [comment]
Somehow it didn't update the opponents username state as intended. As in many cases, simplifying was the solution. Why was it even a state in the first place :D Also, in the most cases, the console should be clean now
This major fix will be pushed with the ingame chat by around tomorrow night.
