### ISSUE TITLE
indicate effects / import decks

### ISSUE THREAD

**Issue by thiagord** [WE-Kaito/digimon-tcg-simulator#110]
First, thank you so much for your wonderfull work! For something done in such a short time is really very good.

I don't know if you're using the duelingbook as a reference, but I think it's really necessary to have an in-game chat to explain/point out effects etc... Maybe even an indicator of effects in the future.

Edit: A system that makes it easy to import decks would be great too!

**Comment by WE-Kaito** [comment]
Thx! Duellingbook was what I had in mind for the projects scope. Ingame Chat is the next feature implemented.

I will keep these features in mind, but don't count on it too soon^^
