### ISSUE TITLE
Mislabeled cards / Token Cards

### ISSUE THREAD

**Issue by Zaffy2** [WE-Kaito/digimon-tcg-simulator#114]
Firstly, just want to give a big thank you for taking on this project, I'm glad that this finally gives the DCG a good, dedicated sim.

I'd like to point out that Flaremon EX5-012 and Crescemon EX5-020 are mislabeled as Digi-Egg cards, rather than Digimon cards, making them unable to be added to the main deck.

Also, as a feature suggestion, I'd like to ask about adding an in-game button to create tokens, if that isn't already in the pipeline.

Thanks for the hard work!

**Comment by WE-Kaito** [comment]
Thank you for the hint. I'll change it manually but of course there can always be more errors like this if it was not reported to digimoncard.io 
Thanks to you I noticed I also forgot to remove the card limit on eosmon and and the d-reaper agent. :D

Didn't know about tokens. Will implement it soon. 🙏
