### ISSUE TITLE
Issue saving deck list

### ISSUE THREAD

**Issue by MaineAcc** [WE-Kaito/digimon-tcg-simulator#115]
I haven’t been able to save a deck. I’ve built a few but I think the page keep reloading itself and not saving my deck. I’ve tried on different devices and even web browsers and nothing is working

**Comment by WintheiserLexus** [comment]
Yeah i think this is a new bug as well. Yesterday i can play and save decks just fine, but now looking at the profile page, it doesnt show the decks anymore.

**Comment by WE-Kaito** [comment]
It's just the performance on my new deployment. Have to monitor this.
I added the loading indicator in todays update.
Good fix, because people have to look at Gatchmon more :)

**Comment by WE-Kaito** [comment]
![Image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/98795399/29f09f29-5d81-4df4-869a-14032c207e66)


... I have to drastically improve performance, change host service or start putting money into it  xD

**Comment by WE-Kaito** [comment]
... good lesson on scalability. 😅
I was fetching ALL the decks and then sort them on the profile page. Should be fixed now?

**Comment by skompc** [comment]
@WE-Kaito was having same problem and can confirm fixed on my end
