### ISSUE TITLE
crashing from field the trash

### ISSUE THREAD

**Issue by GhostTurt** [WE-Kaito/digimon-tcg-simulator#122]
Whenever I would move a card from the field to the trash, usually when done quickly, the game disappears entirely. It has happened multiple times but I think it might just be something with the amount of icons around the trash or something.

**Comment by WE-Kaito** [comment]
I think it's because the attack animation is still attached to it? Or does this happen in general?

the dynamic arrows make the frontend break. 
Maybe I should prevent dragging cards entirely as long as the animation is playing.

**Comment by GhostTurt** [comment]
I actaully do remember one of the crashes was when the opponent declared an attack and trashed a card while the arrow was up.
