### ISSUE TITLE
Some QoL suggestions

### ISSUE THREAD

**Issue by Realsoter** [WE-Kaito/digimon-tcg-simulator#125]
Hello, great job making this sim. I really appreciate the effort.
I have some suggestions to make it more user friendly.
There are already requests for some of them but I am going to list them anyways.
  - [x] I would really like for a button to target things to be implemented. By target I mean click on my cards to show that I am using an effect also click on opponent cards to show him the targets of my effects. A glowing animation would be nice to indicate the use of effects.
 -  [x]  Have a number indicator on cards on both players' hands,decks,trashes so we dont have to manually count them.
 -  [x] A better way to handle stacks with multiple sources.
 -  [x] Some times mulligan option isnt shown.
 -  [x] A button to shuffle security without opening it for effects like T.K which recovers 1 before shuffling so you dont get to see what cards you recovered from deck.
 -  [x] A chat log which keeps track of every move being made so we know if our opponent actually bottom or top decked the cards after searching effects. You can easily cheat as is now.
  - [x] A button to trash from top of deck.
 -  [x] A way to look on X number of cards at the bottom of the deck in we bottom decked something that wasnt meant to go there.
 -  [x] Add a sound when someone invites me for a game because I am usually alt tabbed so that I dont miss any.
   
I think thats all for now. Thanks in advance!!!

**Comment by Realsoter** [comment]
If the boxes that have been ticked mean that you have already implemented them into the game I dont see the 1st one you ticked that is to show a number indicator on decks , hands and trashes. If it means that they are work in progress ignore this message ^^

The hand indicator is mostly usefull if someone plays the Gaomon deck because its a hassle counting them manually every time. Speaking of which it would be nice if we could target cards in our opponents hands for the effect specifically of Miragegaogamon Burst mode because there is no alternative as of right now unless I type in chat e.g. bottom the 1st,2nd 3rd etc. which is a hassle too :D

Have a great day!!!

**Comment by WE-Kaito** [comment]
Figured it's unnecessary on a hand with 5 or less cards. But the other numbers where always there. Are you using light mode, because I just changed those colors after some people seemed to have issues reading the ui :D

Anyways, thx for nicely listing suggestions!

**Comment by Realsoter** [comment]
Yeah I was using light mode. All good now.
