### ISSUE TITLE
Tamers

### ISSUE THREAD

**Issue by GhostTurt** [WE-Kaito/digimon-tcg-simulator#127]
Tamers that such as Taiki, Kiriha, Yuu, and the Hunters need would need to indicate what digimon are underneath what tamer in the tamer area. This probably is just a quick fix and making the tamer area also similar to the battle area. So we don't have to lie about how many digimon are under a tamer so BWG blows up an empty tamer.

**Comment by WE-Kaito** [comment]
Didn't know about that, so I never planned ahead for that case. :/
Making multiple Tamer fields like the Digimon Area would now be a limiting solution and / or require some more work. 

My fix for now: It's all still one field.
Digimon following a Tamer Card will be appended beneath,  so it's always clear to which Tamer one Digimon Belongs. But to to attach a digimon to a Tamer who came first, you will have to rearrange manually.
If a Tamer gets removed first, their Digimon cards will move to the Tamer before.

**Comment by GhostTurt** [comment]
a maximum amount of tamers could just be 4 since Hunters at full power is at 4 but they can also just place their tamers in the battle area cause they do go over. 4 is also just a good number because besides hunters, Blue Flare, and Bagra only really need 2 tamers while Xros Heart typically has 2-4 tamers. That said, theses decks don't really swarm the field with digimon so people could just put their tamers in the battle area instead
