### ISSUE TITLE
Suggestion: Use Digimoncard.app rather than Digimoncard.io

### ISSUE THREAD

**Issue by Antinomy2595** [WE-Kaito/digimon-tcg-simulator#135]
Digimoncard.io is notorious for having missing or incorrect card information on their site, whereas Digimoncard.app pulls its information directly from the Digimon TCG Wiki, which is kept up to date and accurate.

There have been a few times now when searching for cards in the deck editor, that a trait for a card has been missing due to Digimoncard.io not listing it. Switching to Digimoncard.app would improve your deck builder tremendously.

**Comment by WE-Kaito** [comment]
😓didn't even know that... What an awesome page!

But I cannot find an API to use. He seems to fetch securely from his private firebase?
And exporting only gives cardnumbers... ? :(

**Comment by Antinomy2595** [comment]
Maybe contact them through their Github, they might be able to make it accessible for you. If you go to digimoncard.app in the 3 line menu in the top corner you can make requests or report issues and it takes you to their Github page. Hopefully they can collaborate with you cos all their stuff gets pulled directly from the Wiki which is the most accurate source

**Comment by Antinomy2595** [comment]
Sorry accidently hit close, my thumb slipped

**Comment by WE-Kaito** [comment]
It's a great suggestion and would make importing cards peobably very easy. However, this would also need adjustments of every piece of code that is tied to the card-model. Let alone completely rebuilding some parts of the deckbuilder.

But I'm positive this is a great future milestone, if this works.
