### ISSUE TITLE
Desync or disconnect

### ISSUE THREAD

**Issue by thiagord** [WE-Kaito/digimon-tcg-simulator#136]
![image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/20910338/eac0786e-b119-4b7e-aa9c-d98cd302b7be)

I think people are getting desync/disconnected from match after being some time idle... Maybe in the same way that sometimes you are editing a deck and when you try to save, it asks you for a password and login again because you were disconnected

**Comment by WE-Kaito** [comment]
looking at the photo I assume at least one of you is using wifi?
If so, does it also happen if both are connected with lan cables (if this is an option for you)?

**Comment by Antinomy2595** [comment]
This is an issue affecting a lot of people using both WiFi and cable connections to the Internet. What happens is, without warning, the opponent can no longer communicate with you and cannot see moves made on your side (and vice versa) as if you've disconnected from eachother. It appears to happen more often when players are idle for around a minute or two, but still happens when not idle too.

**Comment by thiagord** [comment]
![Image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/20910338/627b98b9-a14e-4345-bdef-d5c837db4359)

@WE-Kaito could they be related?

**Comment by WE-Kaito** [comment]
@thiagord @Antinomy2595 this is the biggest issue right now (together with memory overusage crashing the server sometimes, which means, the current state is not scalable for many users anyways). This is why I prioritized getting all the smaller fixes done first.
Idling in Lobby is one thing, but as stated above, this also occurs right after making moves ingame.

I'll try getting an experimental update regarding idle connections out by tomorrow night. 
It's also time setting up a discord server for this project and get more people involved. Sorry for the inconvencience. I'd love to see this working properly as soon as possible ^^

**Comment by WE-Kaito** [comment]
If it is just an idle-timeout, it could be fixed now. Looking forward to your feedback

**Comment by thiagord** [comment]
Yeah Desync is still a problem

![Image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/20910338/36fd4eef-fdf8-4e9b-aaea-2b407309b9d2)

**Comment by duarm** [comment]
How exactly was this fixed, just started playing and we're getting disconnected all the time, no errors on console
