### ISSUE TITLE
Deckbuilder, unable to add digitama when deck is full.

### ISSUE THREAD

**Issue by Rehnay** [WE-Kaito/digimon-tcg-simulator#137]
As described if you have a 50 card main deck you can no longer add digi-tama. Seems like there are checks in place to validate digi-tama as something else when they're in the deck, but not when a deck is already full with 50 main cards.

**Comment by GhostTurt** [comment]
had the same problem but figured out you just need to remove one card from your deck then you can add your digi-eggs and then put back the same card you removed afterwards
