### ISSUE TITLE
minor cheating

### ISSUE THREAD

**Issue by GhostTurt** [WE-Kaito/digimon-tcg-simulator#141]
So while I was expermenting with 2 accounts. I realized that if you use any action that reveals cards, either the security or eyeball icon, then your opponent is able to drag that card to their security or to their deck and claim it as their own. Of course no one is foolish enough to do this but it was weird that the player could do that.
![Steal (1)](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/130789164/dc236a5b-c6c9-4134-974e-8b756a7ef3e0)
![Steal (2)](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/130789164/ee7e7011-5614-46c0-b9a6-58779de4598d)
![Steal (3)](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/130789164/06b68688-1bd8-4d93-9d97-28ccd11838b2)

**Comment by WE-Kaito** [comment]
Never tested it. thx 😅
