### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Antinomy2595** [WE-Kaito/digimon-tcg-simulator#142]
Currently when spawning a Token, an image doesn't appear for it in the Battle Area, making it hard to keep track of and difficult to see whether or not it is suspended.

**Comment by WE-Kaito** [comment]
Can you replicate this bug, maybe provide a screenshot?

**Comment by WE-Kaito** [comment]
The import path on the Token image was wrong for the deployment! Thx!
