### ISSUE TITLE
Font color and contrast in deckbuilder and ingame log QoL suggestions.

### ISSUE THREAD

**Issue by SSJ-Luffy** [WE-Kaito/digimon-tcg-simulator#145]
In the deckbuilder, the text inside the boxes are kinda hard to see, either make the background brighter or the font color white.
Also for the ingame log, it's probably good to make P1 red and P2 blue for example.
Best solution is probably custom colors, but not sure if it's doable.

**Comment by WE-Kaito** [comment]
I never even consider people using light mode.😅

Just switched and now I know exactly what you mean. Also, I'm blind now.
