### ISSUE TITLE
Small Qol update that will make games really faster

### ISSUE THREAD

**Issue by thiagord** [WE-Kaito/digimon-tcg-simulator#150]
I was thinking about a solution to get cards back to the deck faster, what do you think?

Something like this
![image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/20910338/79cc7560-7bb7-4214-ba13-1472fd421c50)
or  this
![image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/20910338/b55227d2-0b09-4158-936d-d8257b0c2406)

You drag the card to where you want the card to go already

**Comment by WE-Kaito** [comment]
I love it! Thx for the visualization. 
First implementation could be tricky (same as adding digivolution cards to the bottom). But I'll keep this in mind as one of the next features.
