### ISSUE TITLE
Suspending Digimon

### ISSUE THREAD

**Issue by GhostTurt** [WE-Kaito/digimon-tcg-simulator#153]
For some strange reason, the opponent is unable to see if your cards are suspended but can still hear the noise of being suspended and unsuspended. The 2 images were taken seconds within each other.
![Suspend (1)](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/130789164/d51b79f4-20f0-4a79-ba45-e7f0e57fd965)
![Suspend (2)](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/130789164/280729e9-60eb-455d-a748-14f8b71349a8)

**Comment by WE-Kaito** [comment]
oops, I accidentially broke it when I was completely removing the drag functionality from opponent-cards. Now suspending should be fixed and enhanced.
