### ISSUE TITLE
Game setup fix

### ISSUE THREAD

**Issue by IcarusIsOutOfTime** [WE-Kaito/digimon-tcg-simulator#154]
Have it so game setup follows proper rules:
Decide who goes first somehow, dice roll or something (winner MUST go first is proper rule)

Draw five cards, decide whether you'd like to keep the hand or not, if you keep it, draw five cards for security then start.

If you decide to mulligan, shuffle the cards back into the deck, draw five, you must keep this hand, and then draw five cards for security.

My primary issue is security is drawn before you decide to mulligan which is not how the game is supposed to go.

**Comment by WE-Kaito** [comment]
![Image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/98795399/90ae942c-9fee-41a0-9d69-a8750f3fd430)


I know the visual representation is lacking, but the logic does indeed follow the rules, if I'm note mistaken? 

Hand cards are distributed before security.
On pressing mulligan everything is shuffled again and distributed in the same sequence.

**Comment by IcarusIsOutOfTime** [comment]
Was not aware when you mulliganed it redid security. It doesn't seem very apparent that it does, because I've talked with others and they also thought security didn't get changed.
