### ISSUE TITLE
ST17-06 Rapidmon swapped values

### ISSUE THREAD

**Issue by DreamRemnant** [WE-Kaito/digimon-tcg-simulator#184]
ST17-06 Rapidmon from Double Typhoon has it's level and cost swapped. Says it's a level 7 with a cost of 4.
![Screenshot 2023-10-30 232950](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/22580559/8ba25190-4025-417f-afb5-874d59553f82)
![Screenshot 2023-10-30 233004](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/22580559/ee47fff0-6247-4013-9bde-6ed017b02010)

**Comment by WE-Kaito** [comment]
don't know if it's fixed but I close this one because it's a digimoncard.io issue
