### ISSUE TITLE
Need help with chat and battle

### ISSUE THREAD

**Issue by Lantern-r** [WE-Kaito/digimon-tcg-simulator#227]
I have successfully set up the server locally, but the chat window does not display the entered messages and does not show the number of online users or the option to invite players.

<img width="1012" alt="image" src="https://github.com/WE-Kaito/digimon-tcg-simulator/assets/64698811/a13cac77-3012-431f-a749-89d15cbf8dd8">

**Comment by WE-Kaito** [comment]
you probably need to adjust the websocket address (ws: and wss:) in Game.tsx and Lobby.tsx

**Comment by Lantern-r** [comment]
May I need to expose 5173 port to public network?

![image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/64698811/c4fc340c-af48-4f20-952c-fdc58d0b4bea)

**Comment by samhv** [comment]
I have the exact same issue and I'm setting up the `websocketUrl` correctly. And if you send a message on the chat, then server crash here:

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

that happen on `handleTextMessage`, in the line `String roomMessage = parts[1];`.


There is defiantly something wrong here, probably either:
- We are missing a record in the database? maybe a chat room record or something like that, idk, I haven't dig on the code
- Either backend or frontend code isn't up to date, and frontend is sending messages that backend doesn't expect

**Comment by samhv** [comment]
oh, I just realized that the issue is that `GameService` is receiving the message when it should be received by `ChatService`.

**Comment by Lantern-r** [comment]
> oh, I just realized that the issue is that `GameService` is receiving the message when it should be received by `ChatService`.

Oho, can you tell me how do you setup up the websocketUrl? 0.0

**Comment by Lantern-r** [comment]
通过重新编译整个项目进行解决
